spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE
  sql:
    init:
      encoding: UTF-8
