spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:kapok;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE
  sql:
    init:
      encoding: UTF-8
  jpa:
    show-sql: true
logging:
  group:
    kapok-data-jpa: debug
